import { NextResponse } from "next/server";

export async function GET() {
  const data = {
    fdRates: [
      {
        bank: "State Bank of India (SBI)",
        shortName: "SBI",
        tenures: [
          { range: "7 days - 45 days", general: 3.00, senior: 3.50 },
          { range: "46 days - 179 days", general: 4.50, senior: 5.00 },
          { range: "180 days - 210 days", general: 5.75, senior: 6.25 },
          { range: "211 days - 364 days", general: 6.00, senior: 6.50 },
          { range: "1 year - 2 years", general: 6.80, senior: 7.30 },
          { range: "2 years - 3 years", general: 7.00, senior: 7.50 },
          { range: "3 years - 5 years", general: 6.75, senior: 7.25 },
          { range: "5 years - 10 years", general: 6.50, senior: 7.00 },
        ],
      },
      {
        bank: "HDFC Bank",
        shortName: "HDFC",
        tenures: [
          { range: "7 days - 14 days", general: 3.00, senior: 3.50 },
          { range: "15 days - 29 days", general: 3.50, senior: 4.00 },
          { range: "30 days - 45 days", general: 3.50, senior: 4.00 },
          { range: "46 days - 90 days", general: 4.50, senior: 5.00 },
          { range: "91 days - 6 months", general: 4.75, senior: 5.25 },
          { range: "6 months - 1 year", general: 6.00, senior: 6.50 },
          { range: "1 year - 15 months", general: 6.60, senior: 7.10 },
          { range: "15 months - 2 years", general: 7.10, senior: 7.60 },
          { range: "2 years - 5 years", general: 7.00, senior: 7.50 },
          { range: "5 years - 10 years", general: 6.90, senior: 7.40 },
        ],
      },
      {
        bank: "ICICI Bank",
        shortName: "ICICI",
        tenures: [
          { range: "7 days - 14 days", general: 3.00, senior: 3.50 },
          { range: "15 days - 29 days", general: 3.50, senior: 4.00 },
          { range: "30 days - 45 days", general: 3.50, senior: 4.00 },
          { range: "46 days - 90 days", general: 4.50, senior: 5.00 },
          { range: "91 days - 184 days", general: 4.75, senior: 5.25 },
          { range: "185 days - 270 days", general: 6.00, senior: 6.50 },
          { range: "271 days - 1 year", general: 6.00, senior: 6.50 },
          { range: "1 year - 2 years", general: 6.70, senior: 7.20 },
          { range: "2 years - 5 years", general: 7.00, senior: 7.50 },
          { range: "5 years - 10 years", general: 6.90, senior: 7.40 },
        ],
      },
      {
        bank: "Punjab National Bank (PNB)",
        shortName: "PNB",
        tenures: [
          { range: "7 days - 14 days", general: 3.00, senior: 3.50 },
          { range: "15 days - 29 days", general: 3.00, senior: 3.50 },
          { range: "30 days - 45 days", general: 3.00, senior: 3.50 },
          { range: "46 days - 90 days", general: 4.50, senior: 5.00 },
          { range: "91 days - 179 days", general: 5.50, senior: 6.00 },
          { range: "180 days - 270 days", general: 6.00, senior: 6.50 },
          { range: "271 days - 1 year", general: 6.25, senior: 6.75 },
          { range: "1 year - 2 years", general: 6.80, senior: 7.30 },
          { range: "2 years - 3 years", general: 7.00, senior: 7.50 },
          { range: "3 years - 5 years", general: 6.50, senior: 7.00 },
          { range: "5 years - 10 years", general: 6.25, senior: 6.75 },
        ],
      },
      {
        bank: "Bank of Baroda",
        shortName: "BOB",
        tenures: [
          { range: "7 days - 14 days", general: 3.00, senior: 3.50 },
          { range: "15 days - 45 days", general: 3.00, senior: 3.50 },
          { range: "46 days - 90 days", general: 4.25, senior: 4.75 },
          { range: "91 days - 120 days", general: 4.75, senior: 5.25 },
          { range: "121 days - 180 days", general: 5.75, senior: 6.25 },
          { range: "181 days - 270 days", general: 6.00, senior: 6.50 },
          { range: "271 days - 1 year", general: 6.25, senior: 6.75 },
          { range: "1 year - 2 years", general: 6.85, senior: 7.35 },
          { range: "2 years - 3 years", general: 7.15, senior: 7.65 },
          { range: "3 years - 5 years", general: 6.80, senior: 7.30 },
          { range: "5 years - 10 years", general: 6.50, senior: 7.00 },
        ],
      },
    ],

    savingsRates: [
      { bank: "State Bank of India (SBI)", shortName: "SBI", rate: 2.70, balanceUpTo: "1 Crore", notes: "Standard rate for balances up to ₹1 Crore" },
      { bank: "HDFC Bank", shortName: "HDFC", rate: 3.00, balanceUpTo: "50 Lakh", notes: "3.50% for balances above ₹50 Lakh" },
      { bank: "ICICI Bank", shortName: "ICICI", rate: 3.00, balanceUpTo: "50 Lakh", notes: "3.50% for balances above ₹50 Lakh" },
      { bank: "Punjab National Bank", shortName: "PNB", rate: 2.70, balanceUpTo: "1 Crore", notes: "Standard rate for balances up to ₹1 Crore" },
      { bank: "Bank of Baroda", shortName: "BOB", rate: 2.75, balanceUpTo: "1 Crore", notes: "Standard rate for balances up to ₹1 Crore" },
      { bank: "Kotak Mahindra Bank", shortName: "Kotak", rate: 3.50, balanceUpTo: "50 Lakh", notes: "Higher rate for savings accounts" },
      { bank: "Axis Bank", shortName: "Axis", rate: 3.00, balanceUpTo: "50 Lakh", notes: "3.50% for balances above ₹50 Lakh" },
      { bank: "IndusInd Bank", shortName: "IndusInd", rate: 3.50, balanceUpTo: "1 Crore", notes: "Competitive savings rate" },
      { bank: "Yes Bank", shortName: "Yes", rate: 4.00, balanceUpTo: "1 Lakh", notes: "Tiered: 4% up to ₹1L, 3.50% for ₹1L-10L, 3.25% above ₹10L" },
      { bank: "RBL Bank", shortName: "RBL", rate: 4.25, balanceUpTo: "3 Lakh", notes: "Tiered rates based on balance" },
    ],

    taxSlabs: {
      oldRegime: {
        name: "Old Tax Regime",
        description: "Traditional regime with deductions and exemptions under various sections (80C, 80D, HRA, etc.)",
        fy: "2024-25",
        slabs: [
          { incomeUpTo: 250000, rate: 0, label: "Up to ₹2,50,000" },
          { incomeFrom: 250001, incomeUpTo: 500000, rate: 5, label: "₹2,50,001 - ₹5,00,000" },
          { incomeFrom: 500001, incomeUpTo: 1000000, rate: 20, label: "₹5,00,001 - ₹10,00,000" },
          { incomeFrom: 1000001, incomeUpTo: null, rate: 30, label: "Above ₹10,00,000" },
        ],
        deductions: [
          { section: "80C", limit: 150000, description: "Investments in PPF, ELSS, LIC, EPF, NSC, home loan principal, etc." },
          { section: "80CCC", limit: 150000, description: "Pension fund contributions (within 80C overall limit)" },
          { section: "80CCD(1)", limit: 150000, description: "NPS contribution (within 80C overall limit)" },
          { section: "80CCD(1B)", limit: 50000, description: "Additional NPS contribution (over and above 80C)" },
          { section: "80D", limit: 25000, description: "Health insurance premium (₹50,000 for senior citizens)" },
          { section: "80DD", limit: 75000, description: "Medical treatment of dependent with disability (₹1,25,000 for severe disability)" },
          { section: "80E", limit: null, description: "Interest on education loan (no limit, up to 8 years)" },
          { section: "80G", limit: null, description: "Donations to charitable organizations (50% or 100% with/without qualifying limit)" },
          { section: "80TTA", limit: 10000, description: "Interest on savings account" },
          { section: "80TTB", limit: 50000, description: "Interest on deposits for senior citizens (replaces 80TTA)" },
          { section: "24(b)", limit: 200000, description: "Interest on home loan for self-occupied property" },
        ],
        surcharge: [
          { incomeAbove: 5000000, rate: 10, label: "Income above ₹50 Lakh" },
          { incomeAbove: 10000000, rate: 15, label: "Income above ₹1 Crore" },
          { incomeAbove: 20000000, rate: 25, label: "Income above ₹2 Crore" },
          { incomeAbove: 50000000, rate: 37, label: "Income above ₹5 Crore" },
        ],
        cess: 4,
      },
      newRegime: {
        name: "New Tax Regime",
        description: "Simplified regime with lower rates but most deductions and exemptions not available. Default regime from FY 2023-24.",
        fy: "2024-25",
        slabs: [
          { incomeUpTo: 300000, rate: 0, label: "Up to ₹3,00,000" },
          { incomeFrom: 300001, incomeUpTo: 700000, rate: 5, label: "₹3,00,001 - ₹7,00,000" },
          { incomeFrom: 700001, incomeUpTo: 1000000, rate: 10, label: "₹7,00,001 - ₹10,00,000" },
          { incomeFrom: 1000001, incomeUpTo: 1200000, rate: 15, label: "₹10,00,001 - ₹12,00,000" },
          { incomeFrom: 1200001, incomeUpTo: 1500000, rate: 20, label: "₹12,00,001 - ₹15,00,000" },
          { incomeFrom: 1500001, incomeUpTo: null, rate: 30, label: "Above ₹15,00,000" },
        ],
        deductions: [
          { section: "80CCD(2)", limit: null, description: "Employer's NPS contribution (up to 14% of basic salary)" },
          { section: "80JJA", limit: null, description: "Deduction for employment of new employees" },
          { section: "80M", limit: null, description: "Dividends from domestic companies / mutual funds" },
          { section: "Standard Deduction", limit: 50000, description: "Standard deduction from salary (introduced in new regime from FY 2024-25)" },
        ],
        rebate: {
          section: "87A",
          limit: 700000,
          rebateAmount: 25000,
          description: "Full tax rebate if taxable income up to ₹7,00,000 (effective no tax up to ₹7 Lakh)",
        },
        surcharge: [
          { incomeAbove: 5000000, rate: 10, label: "Income above ₹50 Lakh" },
          { incomeAbove: 10000000, rate: 15, label: "Income above ₹1 Crore" },
          { incomeAbove: 20000000, rate: 25, label: "Income above ₹2 Crore" },
        ],
        cess: 4,
      },
    },

    schemes: [
      {
        name: "Public Provident Fund (PPF)",
        shortName: "PPF",
        interestRate: 7.1,
        compounding: "Annual",
        tenure: "15 years (extendable in blocks of 5 years)",
        taxBenefits: "EEE - Exempt on investment (80C), Exempt on interest, Exempt on maturity",
        minInvestment: 500,
        maxInvestment: 150000,
        minInvestmentPer: "year",
        maxInvestmentPer: "year",
        depositFrequency: "Minimum once per year",
        loanFacility: "Available from 3rd to 6th year",
        prematureWithdrawal: "After 5 years (subject to conditions)",
        riskLevel: "Very Low",
        backedBy: "Government of India",
      },
      {
        name: "National Pension System (NPS)",
        shortName: "NPS",
        interestRate: null,
        interestRateNote: "Market-linked (historically 9-12% returns)",
        compounding: "Market-linked",
        tenure: "Till age 60 (partial withdrawal allowed after 3 years)",
        taxBenefits: "80CCD(1) up to ₹1.5L, 80CCD(1B) additional ₹50K, 80CCD(2) employer contribution up to 14% of basic",
        minInvestment: 500,
        maxInvestment: null,
        minInvestmentPer: "contribution",
        maxInvestmentPer: null,
        depositFrequency: "Minimum once per year",
        prematureWithdrawal: "After 3 years for specific purposes (up to 25% of contribution)",
        maturity: "60% tax-free lumpsum + 40% mandatory annuity at age 60",
        riskLevel: "Moderate",
        backedBy: "PFRDA (Government of India)",
      },
      {
        name: "Sukanya Samriddhi Yojana",
        shortName: "SSY",
        interestRate: 8.2,
        compounding: "Annual",
        tenure: "21 years from account opening or until marriage after 18 years",
        taxBenefits: "EEE - Exempt on investment (80C), Exempt on interest, Exempt on maturity",
        minInvestment: 250,
        maxInvestment: 150000,
        minInvestmentPer: "year",
        maxInvestmentPer: "year",
        depositFrequency: "Minimum once per year for 15 years",
        eligibility: "Girl child below 10 years (max 2 accounts per family, 3 for twins)",
        prematureWithdrawal: "Up to 50% for higher education after age 18",
        riskLevel: "Very Low",
        backedBy: "Government of India",
      },
      {
        name: "Senior Citizen Savings Scheme",
        shortName: "SCSS",
        interestRate: 8.2,
        compounding: "Quarterly",
        tenure: "5 years (extendable by 3 years)",
        taxBenefits: "Investment eligible under Section 80C (within ₹1.5L limit). Interest taxable.",
        minInvestment: 1000,
        maxInvestment: 3000000,
        minInvestmentPer: "account",
        maxInvestmentPer: "account",
        depositFrequency: "Lump sum at account opening",
        eligibility: "Age 60+ (55-60 for retired on superannuation)",
        prematureWithdrawal: "After 1 year with penalty (1.5% after 1yr, 1% after 2yr)",
        riskLevel: "Very Low",
        backedBy: "Government of India",
      },
      {
        name: "Kisan Vikas Patra",
        shortName: "KVP",
        interestRate: 7.5,
        compounding: "Annual",
        tenure: "115 months (9 years 7 months - doubles your money)",
        taxBenefits: "No 80C benefit on investment. Interest fully taxable.",
        minInvestment: 1000,
        maxInvestment: null,
        minInvestmentPer: "certificate",
        maxInvestmentPer: null,
        depositFrequency: "Lump sum",
        prematureWithdrawal: "After 2 years 6 months (with conditions)",
        riskLevel: "Very Low",
        backedBy: "Government of India",
      },
      {
        name: "National Savings Certificate",
        shortName: "NSC",
        interestRate: 7.7,
        compounding: "Annual (compounded but paid at maturity)",
        tenure: "5 years",
        taxBenefits: "Investment eligible under Section 80C. Interest reinvested qualifies for 80C (except final year).",
        minInvestment: 1000,
        maxInvestment: null,
        minInvestmentPer: "certificate",
        maxInvestmentPer: null,
        depositFrequency: "Lump sum",
        prematureWithdrawal: "Not allowed (except in exceptional circumstances)",
        riskLevel: "Very Low",
        backedBy: "Government of India",
      },
    ],

    section80C: {
      section: "80C",
      overallLimit: 150000,
      description: "Deduction from gross total income for specified investments and expenses",
      fy: "2024-25",
      investments: [
        { name: "Public Provident Fund (PPF)", type: "Investment", limit: "Within overall ₹1.5L", notes: "15-year lock-in, EEE status" },
        { name: "Employee Provident Fund (EPF)", type: "Investment", limit: "Within overall ₹1.5L", notes: "12% of basic salary (employer + employee)" },
        { name: "Equity Linked Savings Scheme (ELSS)", type: "Investment", limit: "Within overall ₹1.5L", notes: "3-year lock-in, market-linked returns" },
        { name: "National Savings Certificate (NSC)", type: "Investment", limit: "Within overall ₹1.5L", notes: "5-year tenure, 7.7% interest" },
        { name: "National Pension System (NPS) - Tier I", type: "Investment", limit: "Within overall ₹1.5L", notes: "Additional ₹50K under 80CCD(1B)" },
        { name: "Sukanya Samriddhi Yojana", type: "Investment", limit: "Within overall ₹1.5L", notes: "For girl child, 8.2% interest, EEE" },
        { name: "Senior Citizen Savings Scheme", type: "Investment", limit: "Within overall ₹1.5L", notes: "For age 60+, 8.2% quarterly interest" },
        { name: "5-Year Fixed Deposit", type: "Investment", limit: "Within overall ₹1.5L", notes: "Tax-saving FD with 5-year lock-in" },
        { name: "Kisan Vikas Patra", type: "Investment", limit: "Within overall ₹1.5L", notes: "Doubles money in 115 months" },
        { name: "Life Insurance Premium", type: "Insurance", limit: "Within overall ₹1.5L", notes: "Premium for self, spouse, children" },
        { name: "Home Loan Principal Repayment", type: "Loan", limit: "Within overall ₹1.5L", notes: "Only principal component qualifies" },
        { name: "Tuition Fees", type: "Expense", limit: "Within overall ₹1.5L", notes: "For up to 2 children (any school/college/university)" },
        { name: "Sukanya Samriddhi Account", type: "Investment", limit: "Within overall ₹1.5L", notes: "Dedicated for girl child's education/marriage" },
        { name: "Post Office Time Deposit (5 Year)", type: "Investment", limit: "Within overall ₹1.5L", notes: "7.5% interest, 5-year lock-in" },
      ],
    },

    sampleQueries: [
      {
        id: 1,
        hindi: "FD की ब्याज दरें क्या हैं?",
        english: "What are current FD interest rates?",
        category: "Fixed Deposits",
      },
      {
        id: 2,
        hindi: "सेविंग्स अकाउंट में कितना ब्याज मिलता है?",
        english: "How much interest do savings accounts give?",
        category: "Savings",
      },
      {
        id: 3,
        hindi: "टैक्स बचाने के लिए सबसे अच्छी स्कीम कौन सी है?",
        english: "Which is the best tax-saving scheme?",
        category: "Tax Saving",
      },
      {
        id: 4,
        hindi: "PPF में निवेश करने के क्या फायदे हैं?",
        english: "What are the benefits of investing in PPF?",
        category: "Investment",
      },
      {
        id: 5,
        hindi: "होम लोन का EMI कैसे कम करें?",
        english: "How to reduce home loan EMI?",
        category: "Loans",
      },
      {
        id: 6,
        hindi: "सीनियर सिटीजन के लिए कौन सी योजना सबसे अच्छी है?",
        english: "Which scheme is best for senior citizens?",
        category: "Senior Citizens",
      },
      {
        id: 7,
        hindi: "म्यूचुअल फंड और FD में क्या अंतर है?",
        english: "What is the difference between mutual fund and FD?",
        category: "Comparison",
      },
      {
        id: 8,
        hindi: "सेक्शन 80C के तहत कौन से निवेश आते हैं?",
        english: "Which investments fall under Section 80C?",
        category: "Tax Saving",
      },
      {
        id: 9,
        hindi: "सुकन्या समृद्धि योजना के फायदे बताएं?",
        english: "Tell me about Sukanya Samriddhi Yojana benefits?",
        category: "Government Schemes",
      },
      {
        id: 10,
        hindi: "नई टैक्स रेजिम में क्या बदलाव हुए हैं?",
        english: "What changes have been made in the new tax regime?",
        category: "Tax",
      },
    ],

    languages: [
      { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
      { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
      { code: "bn", name: "Bengali", nativeName: "বাংলা" },
      { code: "te", name: "Telugu", nativeName: "తెలుగు" },
      { code: "mr", name: "Marathi", nativeName: "मराठी" },
      { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
      { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
      { code: "en", name: "English", nativeName: "English" },
    ],

    digitalPayments: {
      upi: {
        name: "Unified Payments Interface (UPI)",
        apps: ["Google Pay", "PhonePe", "Paytm", "BHIM", "Amazon Pay", "WhatsApp Pay"],
        transactionLimits: {
          perTransaction: 100000,
          perDay: 100000,
          notes: "₹1 Lakh per transaction per day. May vary by bank (some allow ₹2 Lakh for merchants)",
        },
        upiLite: {
          description: "Offline-capable UPI for small transactions without PIN",
          maxBalance: 2000,
          maxTransaction: 500,
          enabledBanks: "Select banks including SBI, HDFC, ICICI, PNB, Kotak",
        },
        upi123Pay: {
          description: "UPI for feature phones (no smartphone/internet required)",
          methods: ["App-based", "Missed call", "Interactive Voice Response (IVR)", "Proximity sound-based"],
        },
        rupayCreditCardOnUPI: {
          description: "Link RuPay credit card to UPI for merchant payments",
          eligibleCards: "RuPay credit cards from select banks",
          notes: "No MDR for transactions up to ₹2,000",
        },
      },
      neft: {
        name: "National Electronic Funds Transfer (NEFT)",
        timing: "24x7x365 (since Dec 2019)",
        limits: "No minimum or maximum limit (bank-specific limits may apply)",
        charges: "No charges for savings bank customers (RBI mandate)",
        settlement: "Batch settlements every half hour (48 batches per day)",
      },
      rtgs: {
        name: "Real Time Gross Settlement (RTGS)",
        timing: "24x7x365 (since Dec 2020)",
        minimumAmount: 200000,
        maximumAmount: null,
        charges: "₹24.50 for ₹2-5L, ₹49.50 for above ₹5L (waived for savings accounts by many banks)",
        settlement: "Real-time, individual settlement",
      },
      imps: {
        name: "Immediate Payment Service (IMPS)",
        timing: "24x7x365",
        maximumAmount: 500000,
        charges: "₹2.50 for up to ₹1L, ₹5 for ₹1-5L (varies by bank)",
        settlement: "Instant, real-time",
      },
      aeps: {
        name: "Aadhaar Enabled Payment System (AePS)",
        description: "Banking services using Aadhaar authentication at BC (Business Correspondent) points",
        services: ["Cash withdrawal", "Cash deposit", "Balance inquiry", "Mini statement"],
        limits: "Up to ₹10,000 per transaction (bank-specific limits)",
      },
      cbdc: {
        name: "e-Rupee (Digital Rupee)",
        description: "Central Bank Digital Currency pilot by RBI",
        types: ["e₹-R (Retail)", "e₹-W (Wholesale)"],
        status: "Pilot phase in select cities with participating banks",
        participatingBanks: ["SBI", "HDFC", "ICICI", "IDFC First", "Kotak", "PNB", "Canara Bank", "Union Bank", "Bank of Baroda"],
        features: "No interest paid on e₹ holdings, can be converted to/from bank deposits",
      },
      accountAggregator: {
        name: "Account Aggregator (AA) Framework",
        description: "RBI-regulated framework for secure, consent-based financial data sharing",
        useCases: ["Loan applications", "Wealth management", "Financial planning", "KYC verification"],
        dataProviders: "Banks, NBFCs, insurance companies, mutual funds, pension funds",
        keyFeature: "User consent required for every data share; data cannot be stored by AA",
      },
      digiLocker: {
        name: "DigiLocker",
        description: "Digital document storage platform by Government of India for paperless KYC",
        documents: ["Aadhaar", "PAN Card", "Driving License", "Vehicle Registration", "Marksheets", "Insurance policies"],
        kycUse: "Accepted by SEBI, IRDAI, and banks for KYC verification",
        storageLimit: "1 GB per user",
      },
    },

    nriBanking: {
      nreVsNro: [
        {
          feature: "Account Type",
          nre: "Non-Resident External (NRE)",
          nro: "Non-Resident Ordinary (NRO)",
        },
        {
          feature: "Repatriation",
          nre: "Fully repatriable (principal + interest)",
          nro: "Interest repatriable; principal up to $1M per FY with documentation",
        },
        {
          feature: "Tax on Interest",
          nre: "Tax-free in India",
          nro: "Taxable (TDS @ 30% + surcharge + cess, lower under DTAA)",
        },
        {
          feature: "Deposit Source",
          nre: "Foreign earnings only",
          nro: "Foreign earnings + Indian income (rent, dividends, pension)",
        },
        {
          feature: "Joint Holding",
          nre: "With another NRI only",
          nro: "With NRI or resident Indian",
        },
        {
          feature: "Currency Risk",
          nre: "Yes (deposited in foreign currency, maintained in INR)",
          nro: "No (maintained in INR)",
        },
      ],
      fcnr: {
        name: "Foreign Currency Non-Resident (FCNR) Deposit",
        currencies: ["USD", "EUR", "GBP", "JPY", "CAD", "AUD", "CHF", "SGD", "HKD", "SEK", "DKK", "NOK"],
        tenures: "1 to 5 years",
        interestRates: {
          USD: "3.50-4.50% (varies by bank and tenure)",
          EUR: "1.50-2.50%",
          GBP: "3.00-4.00%",
        },
        taxStatus: "Interest fully exempt from Indian income tax",
        repatriation: "Fully repatriable (principal + interest)",
        prematureWithdrawal: "Allowed after 1 year with penalty",
      },
      repatriation: {
        nreAccount: "Unlimited — both principal and interest fully repatriable",
        nroAccount: "Up to USD 1 million per financial year (net of applicable taxes) with CA certificate",
        fcnrDeposit: "Fully repatriable — principal and interest",
        saleOfProperty: "Up to USD 1 million per FY for NRI, subject to capital gains tax",
        inheritance: "Up to USD 1 million per FY with documentation",
      },
      pis: {
        name: "Portfolio Investment Scheme (PIS)",
        description: "RBI scheme allowing NRIs to invest in Indian stock markets",
        eligibility: "All NRIs and OCIs",
        investmentLimit: "Individual: up to 5% of paid-up capital per company; Total NRI: up to 10% (can be increased to 24% by company resolution)",
        designatedBank: "Must route through a designated authorized dealer bank",
        restrictions: "Cannot trade in derivatives, F&O, or intraday. Only delivery-based trades.",
        tax: "Capital gains tax applicable (STCG 20%, LTCG 12.5% above ₹1.25L for equity)",
      },
      tdsOnNRO: {
        description: "TDS rates on NRO account income",
        interest: "30% + surcharge + 4% cess",
        rent: "30% + surcharge + 4% cess",
        dividends: "10% (above ₹5,000; 20% if PAN not provided)",
        capitalGains: "As per applicable capital gains tax rate (STCG/LTCG)",
        dtaaBenefit: "Lower withholding rate as per DTAA (e.g., 10-15% for many countries) with Form 10F and Tax Residency Certificate",
      },
    },

    msme: {
      mudra: {
        name: "MUDRA Yojana (Micro Units Development and Refinance Agency)",
        categories: [
          { name: "Shishu", loanAmount: "Up to ₹50,000", interestRate: "Base rate + 1-3%", tenure: "Up to 5 years", collateral: "No collateral required" },
          { name: "Kishore", loanAmount: "₹50,001 to ₹5,00,000", interestRate: "Base rate + 2-4%", tenure: "Up to 7 years", collateral: "No collateral for up to ₹2L" },
          { name: "Tarun", loanAmount: "₹5,00,001 to ₹10,00,000", interestRate: "Base rate + 3-5%", tenure: "Up to 7 years", collateral: "Bank's discretion" },
        ],
        eligibility: "Any non-corporate, non-farm micro enterprise engaged in manufacturing, trading, or services",
        applyingBanks: "All scheduled commercial banks, RRBs, MFIs, NBFCs",
      },
      gstRegistration: {
        threshold: [
          { type: "Goods (Normal category states)", turnover: 4000000, note: "₹40 Lakh (₹20 Lakh for NE/special category states)" },
          { type: "Services (Normal category states)", turnover: 2000000, note: "₹20 Lakh (₹10 Lakh for NE/special category states)" },
          { type: "Inter-state supply", turnover: 2000000, note: "₹20 Lakh mandatory registration regardless of turnover" },
          { type: "E-commerce operators", turnover: 0, note: "Mandatory registration regardless of turnover" },
        ],
        compositionScheme: {
          eligibility: "Turnover up to ₹1.5 Crore (₹75 Lakh for NE/special category states)",
          taxRates: [
            { category: "Goods (manufacturers/traders)", rate: "1% (0.5% CGST + 0.5% SGST)" },
            { category: "Restaurants (not serving alcohol)", rate: "5% (2.5% CGST + 2.5% SGST)" },
            { category: "Service providers (turnover up to ₹50L)", rate: "6% (3% CGST + 3% SGST)" },
          ],
          benefits: "Simplified compliance, quarterly return (GSTR-4), lower tax rate",
          restrictions: "No inter-state supply, no Input Tax Credit, no e-commerce supply",
        },
      },
      msmeClassification: [
        { type: "Micro", investmentInPlant: "Up to ₹1 Crore", investmentInEquipment: "Up to ₹1 Crore", turnover: "Up to ₹5 Crore" },
        { type: "Small", investmentInPlant: "Up to ₹10 Crore", investmentInEquipment: "Up to ₹10 Crore", turnover: "Up to ₹50 Crore" },
        { type: "Medium", investmentInPlant: "Up to ₹50 Crore", investmentInEquipment: "Up to ₹50 Crore", turnover: "Up to ₹250 Crore" },
      ],
      sidbiSchemes: [
        { name: "SIDBI Direct Assistance", description: "Direct lending to MSMEs for expansion, modernization, technology upgradation", loanRange: "₹10 Lakh to ₹5 Crore" },
        { name: "SIDBI Make in India Soft Loan Fund", description: "Soft loans for MSMEs in manufacturing under Make in India", interestRate: "Base rate - 2%" },
        { name: "SIDBI Startup Fund", description: "Equity and quasi-equity support to startups", focus: "Innovation-driven startups" },
        { name: "CGTMSE (Credit Guarantee Fund Trust for Micro and Small Enterprises)", description: "Guarantee cover for collateral-free loans up to ₹2 Crore", guaranteeCoverage: "Up to 85% for loans up to ₹5L, 75% for above ₹5L" },
      ],
      startupIndia: [
        { name: "Tax Exemption under Section 80-IAC", description: "100% tax exemption for eligible startups for any 3 consecutive years out of first 10 years", eligibility: "DPIIT-recognized startups incorporated after 1 Apr 2016" },
        { name: "Angel Tax Exemption (Section 56(2)(viib))", description: "Exemption from angel tax on investments above fair market value", eligibility: "DPIIT-recognized startups with aggregate paid-up share capital ≤ ₹25 Crore" },
        { name: "Seed Fund Scheme", description: "Financial assistance up to ₹20 Lakh for validation/proof of concept and up to ₹50 Lakh for market entry", eligibility: "DPIIT-recognized startups" },
      ],
    },

    mutualFundCategories: [
      { category: "Large Cap Fund", description: "Invests minimum 80% in top 100 companies by market cap", riskLevel: "Low to Moderate", suitableFor: "Conservative investors seeking stable growth" },
      { category: "Mid Cap Fund", description: "Invests minimum 65% in 101st-250th companies by market cap", riskLevel: "Moderate to High", suitableFor: "Investors with moderate risk appetite" },
      { category: "Small Cap Fund", description: "Invests minimum 65% in companies ranked 251st and below", riskLevel: "High", suitableFor: "Aggressive investors with long-term horizon" },
      { category: "Flexi Cap Fund", description: "Can invest across large, mid, and small cap without restriction", riskLevel: "Moderate to High", suitableFor: "Investors wanting flexible allocation" },
      { category: "Multi Cap Fund", description: "Minimum 25% each in large, mid, and small cap (total 75% equity minimum)", riskLevel: "Moderate to High", suitableFor: "Diversified equity exposure" },
      { category: "Sectoral/Thematic Fund", description: "Invests in a specific sector (banking, pharma, IT) or theme (ESG, consumption)", riskLevel: "Very High", suitableFor: "Investors with sector conviction" },
      { category: "ELSS (Equity Linked Savings Scheme)", description: "Equity fund with 3-year lock-in, qualifies for Section 80C deduction up to ₹1.5L", riskLevel: "Moderate to High", suitableFor: "Tax saving with equity growth" },
      { category: "Liquid Fund", description: "Invests in short-term debt instruments (up to 91 days maturity)", riskLevel: "Very Low", suitableFor: "Parking surplus funds, emergency corpus" },
      { category: "Overnight Fund", description: "Invests in overnight securities (1-day maturity)", riskLevel: "Lowest", suitableFor: "Ultra-short-term parking" },
      { category: "Money Market Fund", description: "Invests in money market instruments (up to 1 year maturity)", riskLevel: "Low", suitableFor: "Short-term investment with slightly better returns than savings" },
      { category: "Gilt Fund", description: "Invests minimum 80% in government securities across maturities", riskLevel: "Moderate (interest rate risk)", suitableFor: "Investors expecting rate cuts" },
      { category: "Corporate Bond Fund", description: "Invests minimum 80% in highest-rated corporate bonds (AA+ and above)", riskLevel: "Low to Moderate", suitableFor: "Stable income with credit quality" },
      { category: "Banking & PSU Fund", description: "Invests minimum 80% in banking and PSU debt instruments", riskLevel: "Low to Moderate", suitableFor: "Sovereign-like safety with better yields" },
      { category: "Dynamic Bond Fund", description: "Can invest across durations and credit qualities; fund manager takes duration calls", riskLevel: "Moderate", suitableFor: "Investors comfortable with active duration management" },
      { category: "Balanced Advantage Fund", description: "Dynamically allocates between equity and debt based on market conditions", riskLevel: "Moderate", suitableFor: "Investors wanting auto asset allocation" },
    ],

    insurance: {
      claimSettlementRatios: [
        { company: "LIC", type: "Life", ratio: 98.52, year: "FY 2023-24" },
        { company: "HDFC Life", type: "Life", ratio: 99.39, year: "FY 2023-24" },
        { company: "SBI Life", type: "Life", ratio: 94.90, year: "FY 2023-24" },
        { company: "ICICI Prudential", type: "Life", ratio: 97.90, year: "FY 2023-24" },
        { company: "Max Life", type: "Life", ratio: 99.35, year: "FY 2023-24" },
        { company: "Tata AIA", type: "Life", ratio: 99.13, year: "FY 2023-24" },
        { company: "Star Health", type: "Health", ratio: 79.20, year: "FY 2023-24" },
        { company: "Niva Bupa", type: "Health", ratio: 89.00, year: "FY 2023-24" },
        { company: "Care Health", type: "Health", ratio: 87.50, year: "FY 2023-24" },
      ],
      pmjjby: {
        name: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        type: "Life Insurance",
        premium: 436,
        premiumPer: "year",
        coverage: 200000,
        coverageDescription: "₹2 Lakh death cover",
        eligibility: "Age 18-50 years with savings bank account",
        enrollment: "Auto-debit from bank account (May-June enrollment period)",
        claimProcess: "Nominee submits claim form + death certificate to bank",
      },
      pmsby: {
        name: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        type: "Accidental Insurance",
        premium: 20,
        premiumPer: "year",
        coverage: [
          { type: "Death / Total Disability", amount: 200000 },
          { type: "Partial Disability", amount: 100000 },
        ],
        eligibility: "Age 18-70 years with savings bank account",
        enrollment: "Auto-debit from bank account (May-June enrollment period)",
      },
      ayushmanBharat: {
        name: "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
        type: "Health Insurance",
        coverage: 500000,
        coveragePer: "family per year",
        coverageDescription: "₹5 Lakh per family per year for secondary and tertiary hospitalization",
        eligibility: "Based on SECC 2011 deprivation criteria; approximately 12 crore families (55 crore beneficiaries)",
        coverageScope: "1,500+ procedures including pre and post hospitalization expenses",
        cashless: true,
        networkHospitals: "28,000+ empaneled hospitals across India",
        portability: "Portable across India — can avail benefits in any empaneled hospital",
      },
      termPlanRiders: [
        { rider: "Critical Illness Rider", description: "Lump sum payout on diagnosis of specified critical illnesses (cancer, heart attack, stroke, etc.)", typicalCost: "₹2,000-5,000/year additional" },
        { rider: "Accidental Death Benefit", description: "Additional sum assured in case of death due to accident", typicalCost: "₹500-1,500/year additional" },
        { rider: "Waiver of Premium", description: "Future premiums waived off on diagnosis of critical illness or disability", typicalCost: "₹1,000-3,000/year additional" },
        { rider: "Income Benefit Rider", description: "Monthly income to family for specified period after death", typicalCost: "₹1,500-4,000/year additional" },
      ],
      healthInsuranceTerms: [
        { term: "Copay", description: "Fixed percentage of claim amount that the policyholder bears (e.g., 10% copay means you pay 10% of bill)", commonIn: "Senior citizen policies, region-specific plans" },
        { term: "Deductible", description: "Fixed amount the policyholder pays before insurance kicks in (e.g., ₹25,000 deductible)", commonIn: "Top-up and super top-up plans" },
        { term: "Room Rent Capping", description: "Limit on room rent (e.g., 1% of sum insured for ICU, 2% for normal room)", commonIn: "Most policies; uncapped is premium feature" },
        { term: "Restoration Benefit", description: "Sum insured is restored (fully/partially) if exhausted during the policy year", commonIn: "Family floater and high-sum insured plans" },
        { term: "Super Top-up vs Top-up", description: "Super top-up: aggregate claims in year exceed deductible; Top-up: single claim exceeds deductible", commonIn: "Supplementary health covers" },
      ],
      pmVVY: {
        name: "Pradhan Mantri Vaya Vandana Yojana (PMVVY)",
        type: "Pension Scheme for Senior Citizens",
        provider: "LIC of India",
        interestRate: 7.40,
        interestRatePer: "year (payable monthly)",
        tenure: "10 years",
        maxPension: 9250,
        maxPensionPer: "month",
        maxInvestment: 1500000,
        eligibility: "Age 60 years and above",
        taxStatus: "GST exempt. Pension income taxable as per slab.",
        prematureExit: "Allowed after 3 years for critical illness with 98% surrender value",
        loan: "Available up to 75% of purchase price after 3 years",
      },
    },
  };

  return NextResponse.json(data, {
    headers: {
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
